![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [20]:
import numpy as np

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [21]:
my_array = np.arange(0,10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [35]:
matriz = np.ones((3,3))
print(matriz)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [38]:
print(my_array[my_array%2 == 1])

[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [42]:
nuevo_array = my_array.copy()
nuevo_array[nuevo_array%2 == 1] = -1
print(nuevo_array)
# print(my_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [43]:
print(np.where(my_array %2 == 1, -1, my_array))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [44]:
my_array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [48]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.concatenate((a,b))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [50]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c2 = np.hstack((a,b))
print(c2)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [65]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c3 = np.intersect1d(a,b)
print(c3)

[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [67]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...),
    axis=0,
    out=None,
    dtype=None,
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [70]:
my_array = np.arange(0,10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [69]:
print(my_array[0])

0


In [72]:
print(my_array[-1])

9


In [73]:
print(my_array[1:8])

[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [76]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [78]:
sec = np.arange(1,50,3)
print(sec)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [87]:
np.random.randint(60,size=((4,5,3)))

array([[[ 8, 22, 44],
        [22, 27,  3],
        [40, 37, 24],
        [58, 50, 50],
        [58, 59,  3]],

       [[12, 51, 51],
        [19, 27, 15],
        [51,  0,  2],
        [12, 36, 31],
        [44, 56, 39]],

       [[ 6, 13, 12],
        [17, 37,  7],
        [10, 21, 19],
        [32, 41, 34],
        [55,  4, 47]],

       [[32, 44, 49],
        [11, 29,  8],
        [11, 45, 10],
        [22, 34, 33],
        [18, 53, 14]]], dtype=int32)

## Ejercicio 16
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [89]:
zero = np.zeros(10).reshape(10,1)
print(zero)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


## Ejercicio 17
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [92]:
x = np.random.randint(10,20,size = (5,2,6))
print(x)
print(f"Número de elementos del array: {x.size}")
print(f"Número de dimensiones: {x.ndim}")
print(f"Longitud de cada dimensión: {x.shape}")

[[[12 17 12 13 12 15]
  [15 14 13 16 14 16]]

 [[12 16 14 12 11 10]
  [13 14 18 18 14 11]]

 [[15 16 14 16 14 15]
  [11 16 16 17 18 18]]

 [[19 13 13 18 14 11]
  [18 16 14 13 14 18]]

 [[13 18 12 17 16 13]
  [16 10 17 12 16 13]]]
Número de elementos del array: 60
Número de dimensiones: 3
Longitud de cada dimensión: (5, 2, 6)
