![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [5]:
my_array = np.arange(0,10)
print(my_array[-1::-2])

[9 7 5 3 1]


In [6]:
"""
my_array = np.arange(10)
print(my_array)
"""

'\nmy_array = np.arange(10)\nprint(my_array)\n'

In [7]:
"""
print(my_array[::-2])
"""

'\nprint(my_array[::-2])\n'

In [8]:
"""
print(my_array[my_array % 2 == 1][::-1])
"""

'\nprint(my_array[my_array % 2 == 1][::-1])\n'

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [12]:
print(my_array[-2:-4:-1])

[8 7]


In [13]:
"""
print(my_array[-2:-4:-1])
"""

'\nprint(my_array[-2:-4:-1])\n'

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [15]:
print(my_array[2::-1])

[2 1 0]


In [14]:
"""
print(my_array[2::-1])
"""

'\nprint(my_array[2::-1])\n'

In [16]:
"""
print(sorted(my_array[:3],reverse=True))
"""

'\nprint(sorted(my_array[:3],reverse=True))\n'

In [ ]:
"""
np.take(my_array, [2,1,0])
"""

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [22]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix[-1::-1,-1::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [23]:
"""
my_matrix.T
"""

'\nmy_matrix.T\n'

In [24]:
"""
print(my_matrix)
"""

'\nprint(my_matrix)\n'

In [25]:
"""
print(my_matrix[::-1,::-1])
"""

'\nprint(my_matrix[::-1,::-1])\n'

In [26]:
"""
print(np.flip(my_matrix))
"""

'\nprint(np.flip(my_matrix))\n'

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [27]:
print(my_matrix[0:2,0:2])


[[1 2]
 [6 7]]


In [28]:
"""
print(my_matrix[:2,:2])
"""

'\nprint(my_matrix[:2,:2])\n'

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [102]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [32]:
print(my_matrix[0::2,0::2])

[[ 1  3  5]
 [11 13 15]]


In [29]:
"""
print(my_matrix[::2,::2])
"""

'\nprint(my_matrix[::2,::2])\n'

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [104]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [34]:
print(my_matrix[0:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


In [35]:
"""
print(my_matrix[:3,::-1])
"""

'\nprint(my_matrix[:3,::-1])\n'

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [37]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [39]:
print("Primera opción")
print(x[x == "Loro"])
print("Segunda opción")
print(np.where(x == "Loro",True,False))

Primera opción
['Loro' 'Loro']
Segunda opción
[ True False False  True False]


In [42]:
"""
x == "Loro"
"""

'\nx == "Loro"\n'

In [43]:
"""
x[x == "Loro"]
"""

'\nx[x == "Loro"]\n'

In [44]:
"""
print(np.where(x== "Loro")[0])
"""

'\nprint(np.where(x== "Loro")[0])\n'

In [45]:
"""
print(np.where(x == "Loro")[0])
"""

'\nprint(np.where(x == "Loro")[0])\n'

In [46]:
"""
x[np.where(x == "Loro")]
"""

'\nx[np.where(x == "Loro")]\n'

In [47]:
# np.where(x == "Loro", x, np.nan)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [113]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [48]:
"""
print(x.ndim)
print(x.shape)
print(x.size)
"""

'\nprint(x.ndim)\nprint(x.shape)\nprint(x.size)\n'

In [49]:
"""
x = np.arange(20).reshape(10,2)
print(x)
m1,m2 = np.vsplit(x,[5])
print()
print(m1)
print()
print(m2)
"""

'\nx = np.arange(20).reshape(10,2)\nprint(x)\nm1,m2 = np.vsplit(x,[5])\nprint()\nprint(m1)\nprint()\nprint(m2)\n'

## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [50]:
cero = np.zeros(10)
print(f"El vector ocupa {cero.nbytes} bytes, que equivale a {cero.nbytes*8} bits.")

El vector ocupa 80 bytes, que equivale a 640 bits.


In [51]:
cero[3] = 1
print(cero)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [ ]:
vector_11 = np.arange(10,50)
print(vector_11)

AttributeError: 'numpy.ndarray' object has no attribute 'sort_values'

In [58]:
vector_11[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [79]:
def dif_0(vector):
    return vector[vector != 0]

vector_12 = np.array([1,2,0,0,4,0])

print(dif_0(vector_12))

[1 2 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [93]:
matriz_13 = np.random.randint(100, size = (10,10))
print(matriz_13)

[[68 66 71 46 90 88 42 63 34  1]
 [65 43 82 72 26 60 90 97 46 61]
 [98  3 22 78 27 64 96 34 98 54]
 [65  4 95 35 28 89 16 93  3  3]
 [55 34 63  8 15 39 61 30 78 72]
 [81 76 76 82 84 52 87 10 94 31]
 [40 80 29 33  4 38 33 23 92 35]
 [93 13 33 41 70 60 70  0  3 41]
 [96 31 38 30 52 53 57 65 35 92]
 [30 89 84 92 87 68 34 74  5 70]]


In [94]:
np.min(matriz_13), np.max(matriz_13)

(np.int32(0), np.int32(98))

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [96]:
random = np.random.rand(30)
print(random)

[0.62838838 0.0289547  0.42320889 0.33492646 0.1584152  0.90577871
 0.16813421 0.09079546 0.36966716 0.23646466 0.76533664 0.74746867
 0.46855728 0.35024648 0.52993715 0.86709071 0.97840211 0.95352929
 0.93369853 0.41543463 0.14341403 0.20260729 0.45993765 0.47728826
 0.95309059 0.09930051 0.96725115 0.34553063 0.49095279 0.06184466]


In [101]:
print(random.mean())

0.4851884287370448


## Ejercicio 15
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [102]:
matriz_rand = np.random.randint(25, size = (5,5))
print(matriz_rand)

[[20 11 23 12  8]
 [16 23  8 23  2]
 [ 0 21 13  8 13]
 [ 0 16  9 22 11]
 [ 0  2 19  1 17]]


In [108]:
media = matriz_rand.mean()
desv = matriz_rand.std()
print(media, desv)

11.92 7.8175187879531185


In [109]:
print((matriz_rand - matriz_rand.mean())/matriz_rand.std())

[[ 1.03357603 -0.1176844   1.4173295   0.01023343 -0.50143787]
 [ 0.52190473  1.4173295  -0.50143787  1.4173295  -1.26894482]
 [-1.52478047  1.16149385  0.13815125 -0.50143787  0.13815125]
 [-1.52478047  0.52190473 -0.37352005  1.28941168 -0.1176844 ]
 [-1.52478047 -1.26894482  0.9056582  -1.39686265  0.64982255]]


## Ejercicio 16
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [121]:
sec = np.arange(11)
print("Apartado 1: \n" , sec)
sec_2 = sec.copy()
sec_2 = np.where((3 <= sec_2)  & (sec_2 <= 8), -1, sec_2)
print("Aapartado 2: \n", sec_2)
sec_3 = sec.copy()
sec_3 = np.where((3 <= sec_3) & (sec_3 <= 8), False, sec_3)
print("Apartado 3:", sec_3)


Apartado 1: 
 [ 0  1  2  3  4  5  6  7  8  9 10]
Aapartado 2: 
 [ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
Apartado 3: [ 0  1  2  0  0  0  0  0  0  9 10]
